#server-url: "http://206.81.22.60:9123/upload"
server-url: "http://localhost:9123/upload"
update-period: 20s
logs-path: "./export/test4"
clinic-id: "test4-local-clinic-id"
device-id: "test4-local-device-id"