#server-url: "http://206.81.22.60:9123/upload"
server-url: "http://localhost:9123/upload"
update-period: 1m
logs-path: "test-logs-examples/export"
clinic-id: "test5-local-clinic-id"
device-id: "test5-local-device-id"
load-files-reg-exp:
  - ^test-logs-examples/Log/Diag/.*
  - ^test-logs-examples/Log/logfile-CSDHomePage-ColNames.txt$
  - ^test-logs-examples/Log/logfile-CSDHomePage.txt$
  - ^test-logs-examples/Log/logfile.txt$
hashes:
  hashes-path: "./hashes.txt"